config/routes.rb
Rails.application.routes.draw do

  root 'profiles#show'
  put '/' => 'profiles#update' #make saving work if at the root

  devise_for :users

  resources :users, only: [:show, :index] do
    resource :profile, only: [:show, :update] do
      get "versions" => :history, as: 'versions'
      post "versions/:id" => "versions#revert", as: "revert_version"
    end
    post "friendship" => "friendships#create"
    delete "friendship" => "friendships#destroy"
  end

  resource :profile, only: [:show, :update] do
    get "versions" => :history, as: 'versions'
    post "versions/:id" => "versions#revert", as: "revert_version"
  end

end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :master, class_name: 'User'
  belongs_to :slave, class_name: 'User'

  def self.between(one, another)
    (Friendship.where(master: one, slave:another) + Friendship.where(master: another, slave: one)).first
  end
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user

  has_paper_trail
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :profile

  has_many :masterships, class_name: 'Friendship', foreign_key: :master_id
  has_many :slaveships, class_name: 'Friendship', foreign_key: :slave_id
  # foreign_key is what this user instance is. :source is what the other user is.
  has_many :masters, through: :slaveships, source: :master
  has_many :slaves, through: :masterships, source: :slave

  def friends(refresh = false)
    masters(refresh) + slaves(refresh)
  end

  def add_friend(newfriend)
    slaves << newfriend
  end

  def remove_friend(oldfriend)
    Friendship.between(self, oldfriend).destroy # :'(
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  before_filter :authenticate_user!

  def create
    newfriend = User.find(params[:user_id])
    current_user.add_friend(newfriend)
    flash[:notice] = "Added #{newfriend.name} as a friend. Note: they can now edit your profile."
    redirect_to users_path
  end

  def destroy
    oldfriend = User.find(params[:user_id])
    flash[:notice] = "Removed #{oldfriend.name} as a friend"
    current_user.remove_friend(oldfriend)
    redirect_to users_path
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  helper :versions

  before_action :get_profile, only: [:show, :edit, :create, :update, :destroy, :history]
  before_filter :authenticate_user!, only: [:create, :destroy]

  def index
    @profiles = Profile.all
  end

  def show
  end

  def edit
  end

  def update
    if logged_in_and_on_strangers_profile? || logged_out_on_existing_profile?
      # catch 403 and show flash in profile.js
      render nothing: true, status: 403 and return
    end

    if @profile.update(params[:profile].permit(:html))
      if user_signed_in?
        flash.now[:notice] = "Saved"
        render json: {status: 'success'} and return
      else
        session[:guestprofile] = @profile.id
        # in javascript: catch 401, show modal
        render nothing: true, status: 401 and return
      end
    end
  end

  def destroy
    @profile.destroy
    redirect_to '/'
  end

  def history
    @versions = @profile.versions
  end

  private
  def logged_in_and_on_strangers_profile?
    user_signed_in? && params[:user_id] && !yours_and_friends_ids.include?(params[:user_id].to_i)
  end

  def yours_and_friends_ids
    [current_user.id] + current_user.friends.map(&:id)
  end

  def logged_out_on_existing_profile?
    !user_signed_in? && params[:user_id]
  end

  def get_profile
    if params[:user_id] # route /users/:user_id/profile
      @profile = User.find(params[:user_id]).profile
    elsif user_signed_in? # routes /profile
      if session[:guestprofile]
        current_user.profile = Profile.find(session[:guestprofile])
        session[:guestprofile] = nil
      end
      @profile = current_user.profile || (current_user.profile = new_profile)
    else #guest
      @profile = new_profile
    end
  end

  def new_profile
    Profile.create(html: '<p id="example_element">Here is an editable html element</p>')
  end

  def authenticate_user!
    if editing_your_own_page?
      super
    elsif params[:user_id]
      flash[:error] = "Can only edit your own or your friends' pages"
      redirect_to user_profile_path(params[:user_id])
    end
  end

  def editing_your_own_page?
    (params[:user_id] && # routes /users/:user_id/profile
      User.find(params[:user_id]) == current_user) ||
      !params[:user_id] # route /profile
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def index
    @users = User.all
  end
end

app/controllers/versions_controller.rb
class VersionsController < ApplicationController
  def revert
    @version = PaperTrail::Version.find(params[:id])
    @version.reify.save!
    redirect_to profile_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
  def viewing_someone_elses_profile?
    if user_signed_in?
      @profile != current_user.profile
    else
      !@profile.user.nil? # not your guest profile
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/versions_helper.rb
module VersionsHelper
  def linkrevert(text, version)
    if @profile.versions.any? && !@profile.versions.last.object.nil?
      link_to text, revert_version_profile_path(version), method: :post, class: "button verbtns"
    else
      'Previous'
    end
  end
end

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Zurb Foundation
.uneditable#flash
  - flash.each do |name, msg|
    - if msg.is_a?(String)
      %div{:class => "alert-box round #{name == :notice ? "success" : "alert"}", "data-alert" => ""}
        = content_tag :div, msg
        %a.close{:href => "#"} &times;

app/views/layouts/_navigation.html.haml
%nav.top-bar{"data-topbar" => true}
  %ul.title-area
    %li.name
      = link_to 'Home', root_path
    %li.toggle-topbar.menu-icon
      %a{:href => "#"}
        %span Menu
  .top-bar-section
    %ul.left
      = render 'layouts/navigation_links'
    %ul.right
      = render 'layouts/user_management'

app/views/layouts/_navigation_links.html.haml
%li= link_to('All users', users_path)

app/views/layouts/_user_management.html.haml
- if user_signed_in?
  %li= link_to('My user stats', user_path(current_user))
  %li= link_to('My sandbox', profile_path)
  %li= link_to('Edit registration', edit_user_registration_path)
  %li= link_to('Logout', destroy_user_session_path, :method => :delete)
- else
  %li= link_to('Login', new_user_session_path)
  %li= link_to('Register', new_user_registration_path)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Websandbox'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Websandbox'}"}
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    -# Modernizr is required for Zurb Foundation
    = javascript_include_tag "vendor/modernizr"
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    %header.uneditable
      = render 'layouts/navigation'
    %main{:role => "main"}
      = render 'layouts/messages'
      = yield
    %script{src: "//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"}

app/views/profiles/_form.html.haml
-#= form_for @profile do |f|
  - if @profile.errors.any?
    #error_explanation
      %h2= "#{pluralize(@profile.errors.count, "error")} prohibited this profile from being saved:"
      %ul
        - @profile.errors.full_messages.each do |msg|
          %li= msg

  .field
    = #f.text_field :whatever

app/views/profiles/_signupmodal.html.haml
#signUpModal.uneditable.reveal-modal{data: {reveal: true}}
  %p.lead
    You need to create an account to save your profile.
    = link_to 'Sign up', new_user_registration_path
    %a.close-reveal-modal &#215;

app/views/profiles/edit.html.haml
%h1 Editing profile

= render 'form'

app/views/profiles/history.html.haml
.medium-10.small-centered.columns
  %table{width: '100%'}
    %thead
      %tr
        %th{width: '200'} Time
        %th{width: '200'} Edited by
        %th Content
        %th{width: '200'}
    %tbody
      - @versions.each do |version|
        %tr.tablerow
          %td= version.created_at
          %td= version.whodunnit && User.find(version.whodunnit).name
          - if version.event == "create"
            %td
              %i profile created
          - else
            %td= truncate(version.reify.html, length: 100)
            %td= linkrevert('Revert to this version', version)

app/views/profiles/index.html.haml
%h1 Listing profiles

- @profiles.each do |profile|
  %tr
    %td= profile.text
    %td= link_to 'Show', profile
    %td= link_to 'Edit', edit_profile_path(profile)
    %td= link_to 'Destroy', profile, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New profile', new_profile_path

app/views/profiles/new.html.haml
%h1 New question

= render 'form'

= link_to 'Back', profile_path

app/views/profiles/show.html.haml
#grid-background.uneditable

= render 'signupmodal'

#versioning.uneditable
  %a.button.verbtns#edit_button Edit
  %a.button.success.verbtns#add_button +
  = linkrevert('Revert to previous version', @profile.versions(true).last)
  %a.alert.button.verbtns#save Save
  -# needs to do an ajax PATCH to /profile with the html in div-editable
  = link_to 'Version history', versions_profile_path, class: "success button verbtns"

- if viewing_someone_elses_profile?
  .secondary.button#profilelink
    = link_to "Viewing #{@profile.user.name}'s sandbox", user_path(@profile.user)

#control_content.uneditable
  .panel#edit_panel
    .row
      .small-6.columns.content#panel-1
        %form
          %label HTML
          %textarea#edit_field_html{cols: '40'}
      .small-6.columns.content#panel-2
        %form
          %label CSS
          %textarea#edit_field_css{cols: '40'}
    .row
      .small-12.columns
        %h5
          %small enter to preview, shift+enter to insert newline
    %a#tag_helpers_button 
      %b +
    #tag_helpers_div
      %ul#tag_helpers(list-style='none')
        %li
          %a(href="#" data-text="<h1></h1>")="<h1>"
        %li
          %a(href="#" data-text="<a href='#'></a>")="<a>"
        %li
          %a(href="#" data-text="<img src='#'>")="<img>"
.profile_content.uneditable#uneditable
  = @profile.html.html_safe

app/views/users/_user.html.haml
%tr
  %td{width: '25%'}= user.name
  %td{width: '35%'}= user.email
  %td{width: '15%'}= link_to 'User page', user, class: "button verbtns"
  %td{width: '10%'}= link_to 'Sandbox', user_profile_path(user), class: "button verbtns"
  - if user_signed_in? && user != current_user
    - if current_user.friends.include? user
      %td{width: '15%'}= button_to 'Remove friend', user_friendship_path(user), method: :delete, class: "alert button verbtns"
    - else
      %td{width: '15%'}= button_to 'Add friend', user_friendship_path(user), class: "button verbtns"

app/views/users/index.html.haml
%h1 All users

.row
  .medium-12.small-centered.columns
    %table{width: '100%'}
      %tbody
        = render @users

app/views/users/show.html.haml
%h1= @user.name


.row
  .medium-6.small-centered.columns
    %table{width: '100%'}
      %thead
        %tr
          %th Friends
      %tbody
        %tr
          - @user.friends.each do |friend|
            %td{width: '30%'}= friend.name
            %td{width: '30%'}= friend.email
            %td{width: '20%'}= link_to 'Friend info', user_page(friend), class: "button verbtns"
            %td{width: '20%'}= link_to 'Sandbox', user_profile_path(friend), class: "button verbtns"


= link_to 'See this user\'s sandbox', user_profile_path(@user)